done = False

while not done:
    prince_princess = raw_input("CHoose either Prince or Princess: ")
    character = raw_input("what is the gender of you characer (Put he or she): ")
    Name = raw_input("Choose a name of your choice: ")
    name1 = raw_input("Enter in another name: ")
    superhero_name = raw_input("Enter a Superhero name: ")
    adjective = raw_input("Enter an adjective: ")
    noun = raw_input("enter a noun: ")
    noun1 = raw_input("enter another noun: ")
    Plural_Noun = raw_input("Enter a plural noun: ")
    Plural_Noun1 = raw_input("Enter another plural noun: ")
    Plural_Noun2 = raw_input("Enter another Plural noun: ")
    place = raw_input("Enter a place: ")
    emotion = raw_input("Enter an emotion: ")
    verb = raw_input("Enter a verb: ")
    adverb = raw_input("Enter an '-ly' adverb: ")
    
    print ("")
    print ("")
    print ("Once upon a time there was a " + prince_princess)
    print ("who went by the name of " + name1)
    print (". "+ character )
    print ("loved to look outside to view the " + noun)
    print (". but then " + character)
    print ("was trapped in a " + noun1) 
    print ("without any " + Plural_Noun) 
    print ("or " + Plural_Noun1)
    print (". " + character)
    print ("was very " + emotion)
    print ("Then one day " + Name)
    print ("came to visit " + name1)
    print ("and said there was a way to escape " + noun1)
    print ("If they found the way out then the would be as free as " + Plural_Noun2)
    print ("but they were too " + adjective)
    print ("to figure out a plan so they were trapped. ")
    print ("Then a superhero by the name of " + superhero_name)
    print ("broke into the " + noun1)
    print ( "" + character)
    print ("were trapped in. They " + verb)
    print ("through the hole and escaped.  Then they lived " + adverb)
    print ("ever after ")
    print ("THE END.")
    print ("")
    print ("")